// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAim2DCCSZ4mG-m89WgXY7c1FkFeT0-vW8',
    appId: '1:102199281876:web:b5ff48a77269200fbc5341',
    messagingSenderId: '102199281876',
    projectId: 'mobile-2d5e2',
    authDomain: 'mobile-2d5e2.firebaseapp.com',
    databaseURL: 'https://mobile-2d5e2-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-2d5e2.appspot.com',
    measurementId: 'G-XV0SKX41Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2k1CAy0n7r3PrybvM5_l2CkKlie56F6Y',
    appId: '1:102199281876:android:eb65222bbc4ceedcbc5341',
    messagingSenderId: '102199281876',
    projectId: 'mobile-2d5e2',
    databaseURL: 'https://mobile-2d5e2-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-2d5e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbX6GoMR6R3coOoiptZXgfZQqo4caJ8Xg',
    appId: '1:102199281876:ios:0cdf0148ab3fa46dbc5341',
    messagingSenderId: '102199281876',
    projectId: 'mobile-2d5e2',
    databaseURL: 'https://mobile-2d5e2-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-2d5e2.appspot.com',
    iosBundleId: 'com.example.mobile',
  );
}
